#include "timers.h"

void SetupPWM( void )
{
	SET_BITS_IN_REG( SIM_SCGC6, SIM_SCGC6_TPM2_MASK );
	SET_BITS_IN_REG( SIM_SCGC6, SIM_SCGC6_TPM0_MASK );

	SET_BITS_IN_REG( TPM2_CONF, TPM_CONF_TRGSEL( 0xA ) );
	SET_BITS_IN_REG( TPM0_CONF, TPM_CONF_TRGSEL( 0xA ) );

	SET_BITS_IN_REG( TPM2_CONF, TPM_CONF_CROT_MASK );
	SET_BITS_IN_REG( TPM0_CONF, TPM_CONF_CROT_MASK );

	SET_BITS_IN_REG( SIM_SOPT2, SIM_SOPT2_TPMSRC( 1 ) );
	
	SET_BITS_IN_REG( TPM2_SC, TPM_SC_CMOD( 1 ) );
	SET_BITS_IN_REG( TPM0_SC, TPM_SC_CMOD( 1 ) );
	
	TPM2_CNT = TPM_CNT_COUNT_MASK;
	TPM0_CNT = TPM_CNT_COUNT_MASK;
	TPM2_MOD = MODULUS;
	TPM0_MOD = MODULUS;
	SET_BITS_IN_REG( TPM2_C0SC, TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK );
	TPM2_C0V = (uint16_t) MODULUS * 0.50;
	SET_BITS_IN_REG( TPM2_C1SC, TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK );
	TPM2_C1V = (uint16_t) MODULUS * 0.50;
	SET_BITS_IN_REG( TPM0_C1SC, TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK );
	TPM0_C0V = (uint16_t) MODULUS * 0.50;
	SET_BITS_IN_REG( TPM0_C1SC, TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK );
	TPM0_C1V = (uint16_t) MODULUS * 0.50;
}

void ChangePW( uint16_t pulseWidth )
{
	uint16_t valueToCnV = (uint16_t) MODULUS * ( pulseWidth / 100.0 );
	TPM2_C0V = valueToCnV;
	TPM2_C1V = valueToCnV;
	TPM0_C1V = valueToCnV;
}
